# -*- coding: utf-8 -*-
"""Challenge Alura final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I20r_pD2dzS93G_6qxdt7Q6qZDzZOa61
"""
import os
import torch
import streamlit as st
from google import genai
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from transformers import pipeline
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# Configuración del entorno
#!pip install -qU google-genai langchain-huggingface sentence-transformers langchain langchain-community pypdf chromadb

try:
    from google.colab import userdata
    api_key = userdata.get('GEMINI_API_KEY_2')
except (ImportError, Exception):
    api_key = os.environ.get('GEMINI_API_KEY_2')

client = genai.Client(api_key=api_key)

#Generación del documento PDF de base de conocimientos para el Centro Médico Vitalis

def generar_pdf_clinica():
    doc = SimpleDocTemplate("consultorio_medico.pdf", pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    styles = getSampleStyleSheet()

    titulo_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, textColor=colors.HexColor("#1A365D"), spaceAfter=12)
    subtitulo_style = ParagraphStyle('SubTitleStyle', parent=styles['Heading2'], fontSize=13, textColor=colors.HexColor("#2B6CB0"), spaceBefore=10, spaceAfter=6)
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=11, leading=14, spaceAfter=8)

    contenido = [
        ("Centro Médico Vitalis - Guía de Información y Políticas al Paciente", titulo_style),
        ("1. Preguntas Frecuentes sobre Consultas y Turnos", subtitulo_style),
        ("• Horario de atención: Lunes a viernes de 08:00 a 20:00 hrs. Sábados de 09:00 a 14:00 hrs.\n"
         "• ¿Cómo agendar cita?: Se puede agendar a través del portal web o por llamada telefónica.\n"
         "• Tiempos de espera: Se recomienda llegar 15 minutos antes de la hora programada para el registro inicial.", body_style),
        ("2. Política de Cancelaciones y Reagendamiento", subtitulo_style),
        ("• Cancelación anticipada: Las citas deben cancelarse o reagendarse con un mínimo de 24 horas de anticipación sin costo alguno.\n"
         "• Penalización por inasistencia: Si se cancela con menos de 24 horas o no se asiste, se aplicará un cargo del 50% de la consulta en la siguiente cita.\n"
         "• Tolerancia de llegada: La tolerancia máxima de retraso es de 10 minutos. Pasado ese tiempo, la cita se considerará cancelada.", body_style),
        ("3. Convenios y Coberturas Médicas", subtitulo_style),
        ("• Seguros aceptados: Trabajamos con MetLife, GNP, AXA Seguros y Sanitas.\n"
         "• Reembolsos: En caso de pago particular, se entregará factura médica para el trámite de reembolso con su aseguradora.", body_style),
        ("4. Instrucciones Pre y Post Consulta", subtitulo_style),
        ("• Análisis de sangre: Requieren ayuno obligatorio de 8 a 12 horas previo al estudio.\n"
         "• Ultrasonido abdominal: Se requiere acudir con 1 litro de agua ingerido una hora antes del examen.\n"
         "• Recetas médicas: Las recetas tienen una vigencia de 30 días naturales para su surtido en farmacia.", body_style),
        ("5. Política de Privacidad de Datos del Paciente", subtitulo_style),
        ("• Resguardo de información: El expediente clínico electrónico está protegido bajo encriptación de grado médico y conforme a las regulaciones de protección de datos personales en salud.", body_style)
    ]

    for texto, estilo in contenido:
        story.append(Paragraph(texto.replace('\n', '<br/>'), estilo))
        story.append(Spacer(1, 4))

    doc.build(story)

if not os.path.exists("consultorio_medico.pdf"):
    generar_pdf_clinica()

#Configuración del pipeline RAG con modelo local y prompt estricto
@st.cache_resource
def cargar_agente_rag():
    loader = PyPDFLoader("consultorio_medico.pdf")
    docs = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=80)
    splits = text_splitter.split_documents(docs)

    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)
    retriever = vectorstore.as_retriever()

    generator = pipeline(
        "text-generation",
        model="Qwen/Qwen2.5-0.5B-Instruct",
        device=-1,  
        torch_dtype=torch.float32
    )
    return retriever, generator

retriever, generator = cargar_agente_rag()

def consultar_agente(pregunta_usuario):
    docs_relevantes = retriever.invoke(pregunta_usuario)

    if not docs_relevantes:
        return "Lo siento, no encontré información sobre eso en los documentos del Centro Médico Vitalis."
         
    contexto = "\n\n".join([doc.page_content for doc in docs_relevantes])
    
    messages = [
        {"role": "system", "content": "Eres un robot asistente del Centro Médico Vitalis (atención HUMANA). Tu regla de oro es: Responde SOLO con el contexto proporcionado. Si la respuesta no está en el contexto, di textualmente: 'No dispongo de esa información en mis documentos.'"},
        {"role": "user", "content": f"CONTEXTO DEL PDF:\n{contexto}\n\nPREGUNTA DEL USUARIO:\n{pregunta_usuario}\n\nRESPUESTA (SI NO ESTÁ EN EL CONTEXTO, DI 'No dispongo de esa información en mis documentos, ¿Tienes alguna otra pregunta?.'):"}
    ]
    
    prompt = generator.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    outputs = generator(prompt, max_new_tokens=150, do_sample=False, temperature=0.0)
    
    respuesta_completa = outputs[0]["generated_text"]
    respuesta_limpia = respuesta_completa.split("<|im_start|>assistant\n")[-1].strip()
    
    return respuesta_limpia
    
#Interfaz interactiva para el usuario
st.title("🏥 Consultorio Médico Vitalis")
st.subheader("Sistema de Consultas RAG")

pregunta = st.text_input("Escribe tu pregunta aquí:")

if st.button("Enviar pregunta"):
    if pregunta.strip():
        with st.spinner("Consultando el documento..."):
            respuesta = consultar_agente(pregunta)
            st.success("Respuesta:")
            st.write(respuesta)
    else:
        st.warning("Por favor escribe una pregunta.")
