# -*- coding: utf-8 -*-
"""Challenge Alura final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I20r_pD2dzS93G_6qxdt7Q6qZDzZOa61
"""
import os
import streamlit as st
from google import genai
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Configuración del entorno
#!pip install -qU google-genai langchain-huggingface sentence-transformers langchain langchain-community pypdf chromadb
api_key = os.environ.get('GEMINI_API_KEY_2')

if not api_key:
    st.error("No se encontró la variable de entorno GEMINI_API_KEY_2 en Render.")
    st.stop()

client = genai.Client(api_key=api_key)

#Generación del documento PDF de base de conocimientos para el Centro Médico Vitalis

def generar_pdf_clinica():
    doc = SimpleDocTemplate("consultorio_medico.pdf", pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    styles = getSampleStyleSheet()

    titulo_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, textColor=colors.HexColor("#1A365D"), spaceAfter=12)
    subtitulo_style = ParagraphStyle('SubTitleStyle', parent=styles['Heading2'], fontSize=13, textColor=colors.HexColor("#2B6CB0"), spaceBefore=10, spaceAfter=6)
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'], fontSize=11, leading=14, spaceAfter=8)

    contenido = [
        ("Centro Médico Vitalis - Guía de Información y Políticas al Paciente", titulo_style),
        ("1. Preguntas Frecuentes sobre Consultas y Turnos", subtitulo_style),
        ("• Horario de atención: Lunes a viernes de 08:00 a 20:00 hrs. Sábados de 09:00 a 14:00 hrs.\n"
         "• ¿Cómo agendar cita?: Se puede agendar a través del portal web o por llamada telefónica.\n"
         "• Tiempos de espera: Se recomienda llegar 15 minutos antes de la hora programada para el registro inicial.", body_style),
        ("2. Política de Cancelaciones y Reagendamiento", subtitulo_style),
        ("• Cancelación anticipada: Las citas deben cancelarse o reagendarse con un mínimo de 24 horas de anticipación sin costo alguno.\n"
         "• Penalización por inasistencia: Si se cancela con menos de 24 horas o no se asiste, se aplicará un cargo del 50% de la consulta en la siguiente cita.\n"
         "• Tolerancia de llegada: La tolerancia máxima de retraso es de 10 minutos. Pasado ese tiempo, la cita se considerará cancelada.", body_style),
        ("3. Convenios y Coberturas Médicas", subtitulo_style),
        ("• Seguros aceptados: Trabajamos con MetLife, GNP, AXA Seguros y Sanitas.\n"
         "• Reembolsos: En caso de pago particular, se entregará factura médica para el trámite de reembolso con su aseguradora.", body_style),
        ("4. Instrucciones Pre y Post Consulta", subtitulo_style),
        ("• Análisis de sangre: Requieren ayuno obligatorio de 8 a 12 horas previo al estudio.\n"
         "• Ultrasonido abdominal: Se requiere acudir con 1 litro de agua ingerido una hora antes del examen.\n"
         "• Recetas médicas: Las recetas tienen una vigencia de 30 días naturales para su surtido en farmacia.", body_style),
        ("5. Política de Privacidad de Datos del Paciente", subtitulo_style),
        ("• Resguardo de información: El expediente clínico electrónico está protegido bajo encriptación de grado médico y conforme a las regulaciones de protección de datos personales en salud.", body_style)
    ]

    for texto, estilo in contenido:
        story.append(Paragraph(texto.replace('\n', '<br/>'), estilo))
        story.append(Spacer(1, 4))

    doc.build(story)

if not os.path.exists("consultorio_medico.pdf"):
    generar_pdf_clinica()
    
#Configuración del pipeline RAG con modelo local y prompt estricto
@st.cache_resource
def obtener_fragmentos_pdf():
    loader = PyPDFLoader("consultorio_medico.pdf")
    docs = loader.load()
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=80)
    return text_splitter.split_documents(docs)

splits = obtener_fragmentos_pdf()

def consultar_agente(pregunta_usuario):
    # Obtenemos todo el contenido relevante del PDF como contexto
    contexto = "\n\n".join([doc.page_content for doc in splits])
    
    prompt = f"""
Eres un robot asistente del Centro Médico Vitalis (atención HUMANA). Tu regla de oro es: Responde SOLO con el contexto proporcionado. Si la respuesta no está en el contexto, di textualmente: 'No dispongo de esa información en mis documentos.'

CONTEXTO DEL PDF:
{contexto}

PREGUNTA DEL USUARIO:
{pregunta_usuario}

RESPUESTA (SI NO ESTÁ EN EL CONTEXTO, DI 'No dispongo de esa información en mis documentos, ¿Tienes alguna otra pregunta?.'):
"""
    
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
    )
    return response.text
    
#Interfaz interactiva para el usuario
st.title("🏥 Centro Médico Vitalis")
st.subheader("Sistema de Consultas e Información")

pregunta = st.text_input("Escribe tu pregunta aquí:")

if st.button("Enviar pregunta"):
    if pregunta.strip():
        with st.spinner("Consultando el documento..."):
            try:
                respuesta = consultar_agente(pregunta)
                st.success("Respuesta:")
                st.write(respuesta)
            except Exception as e:
                st.error(f"Ocurrió un error: {e}")
    else:
        st.warning("Por favor escribe una pregunta.")
